### ISSUE TITLE
Clarifying licensing and attribution

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-up-changelog#1]
@rhendric This repo is my (WIP) attempt at porting [PureScript's `update-changelog.hs`](https://github.com/purescript/purescript/blob/master/update-changelog.hs) script that you wrote from Haskell to PureScript. Since you are the original author behind it and I am merely porting it, I wanted to ask a few questions out of respect for you:
1. Per the [`CONTRIBUTING.md`](https://github.com/purescript/purescript/blob/master/CONTRIBUTORS.md) file, the work you've contributed to the PS repo, including this script, is licensed under MIT. While I can do likewise here, is there a different license you would prefer this be licensed under?
2. What acknowledgement / attribution do you want (if any) for the script in this repo?

My larger goal is to publish this script as an NPM package, so that we can use it throughout core, contrib, web, and node libraries while doing the PS v0.15.x ecosystem update.

**Comment by rhendric** [comment]
Neat! I'm easy; I'd be happy for this to continue to be MIT-licensed, or I'd be happy to relicense my work to you under a GPL-family license. In either case, linking back to the PureScript origins of this in some way seems like a good idea, whether or not my name is used explicitly, and I consider that link to be sufficient acknowledgement.

**Comment by JordanMartinez** [comment]
Great! I'll continue to license this as MIT. How about I link back to the https://github.com/purescript/purescript/pull/4132 since that was the original PR that added the script? It includes some discussion on the design as well.

**Comment by rhendric** [comment]
Sounds good!

**Comment by JordanMartinez** [comment]
Closed by 5cc837521ea687242b8fbb5fc6e4bef8a582a314

Thanks!
